version: "3.8"
services:
  fix-perms:
    image: ubuntu
    command: chown -R $HOST_UID:$HOST_UID /Zomboid
    volumes:
      - ./config/Zomboid:/Zomboid
  server:
    build:
      context: dockerfile
      args:
        - HOST_UID
    image: pz-dedicated-server
    restart: on-failure
    ports:
      - "$STEAM_PORT:16261/udp"
      - "$DIRECT_PORT:16262/udp"
      - "$RCON_PORT:27015"
    volumes:
      - ./scripts:/home/zomboid/scripts
      - ./config/Zomboid:/home/zomboid/Zomboid

      - "game-data:/home/zomboid/Steam/steamapps/common/Project Zomboid Dedicated Server"

      - "./config/jvm-config.json:/home/zomboid/Steam/steamapps/common/Project Zomboid Dedicated Server/ProjectZomboid64.json"
    environment:
      - SERVER_NAME
    depends_on:
      fix-perms:
        condition: service_completed_successfully
    secrets:
      - admin-password
volumes:
  game-data:
secrets:
  admin-password:
    file: secrets/admin-password
