#!/bin/bash
set -euo pipefail

source "$(dirname "$0")"/lib.sh

if world_exists; then
    echo "Starting server"
    run_server
else
    echo "World does not exist. Running server once to create config files..."
    initial_run
    echo "Initial server run complete. Check config/Server folder for '$SERVER_NAME' configuration files."
fi
